# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_id = belts
mod_version = 2.0.0-exp1-pf.1
maven_group = de.rearth
archives_name = belts

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
neoforge_version = 26.1.2.77
