architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    implementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    compileOnly "curse.maven:ftb-filter-system-943925:8300190"

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
